name: day_night_switch
description: An easy to implement custom day night switch widget for Flutter. It can be highly customized with day & night colors and images.
version: 1.0.4
homepage: https://github.com/divyanshub024/day_night_switch
repository: https://github.com/divyanshub024/day_night_switch
issue_tracker: https://github.com/divyanshub024/day_night_switch/issues
documentation: https://github.com/divyanshub024/day_night_switch/blob/master/README.md

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
